### ISSUE TITLE
ERROR: aws-serverless-express connection error on DELETE request

### ISSUE THREAD

**Issue by cliffgibson** [awslabs/aws-serverless-express#106] opened 2017-11-03 03:19 UTC
I just follow the example to wrap my Express application. There is a "app.delete" handler in my app. When DELETE request is being served, there is strange error thrown out from aws-serverless-express, as shown below

ERROR: aws-serverless-express connection error
{ Error: socket hang up at createHangUpError (_http_client.js:253:15) at Socket.socketOnEnd (_http_client.js:345:23)

My code is very simple:

app.delete('/user', routes.user.remove);
module.exports.remove = [
	(request, response) => {
		let user = request.body;
		console.log('remove user='+JSON.stringify(user));
		db.users.delete(user.username, (err) => {
			if (err) {
				response.status(500).send('internal error');
			}
			else {
				response.json({ username: user.username });
			}
		});
	}
];

Just for testing purpose, if I replace the app.delete handler with app.patch, and invoke the call using HTTP PATCH method, with exactly same request parameters, the call is handled correctly. And this is my workaround for the moment. 

Pls help. Thank you

**Comment by ro-tex** [comment] 2018-01-31 14:19
It might sound silly but... can you double-check that you are not accidentally sending a request body with the DELETE request? I know I've done it while testing with Postman.

**Comment by brettstack** [comment] 2018-04-10 20:35
@cliffgibson please confirm: did the DELETE request have a body? I will try to reproduce.

**Comment by novemberde** [comment] 2018-04-11 08:53
@cliffgibson DELETE request is not supported response body. Please use POST or PUT method instead of DELETE If you really want to get a response body.

**Comment by ro-tex** [comment] 2018-04-11 16:47
@novemberde the issue is not that we want to *receive* a body. We want to be able to *send* a body without getting a 502 error. The RFC allows for that.

**Comment by novemberde** [comment] 2018-04-13 04:48
@brettstack Yes, DELETE works on Express app. 
here's code.
const app = require("express")();
app.delete("/", (req, res, next) => {
    res.status(200).json({
        message: "Receive body on DELETE Method!"
    });
 });
app.listen(3000, () => console.log("Running!"));

**Comment by SeanLMcCullough** [comment] 2018-05-08 22:49
Encountered the same issue, and it's especially infuriating when you have the same code executed by PUT and DELETE but DELETE crashes without a single understandable error message. This should be fixed, the RFC HTTP1.1 spec doesn't forbid the use or request body on DELETE commands, and as such - express supports it.

I don't have the time to confirm this, but does API Gateway support request body on DELETE?

**Comment by HotelCalifornia** [comment] 2018-05-30 18:03
Have there been any updates on this?

**Comment by HotelCalifornia** [comment] 2018-05-30 18:52
Also:

> I don't have the time to confirm this, but does API Gateway support request body on DELETE?

I've just confirmed that it does. Somewhere along the line it seems that this module is dropping the body for DELETE requests

**Comment by guzmonne** [comment] 2018-06-13 20:52
I am also having an issue with this. Does anyone knows a workaround to this bug that doesn't involve changing the DELETE method to a PUT method?

**Comment by brettstack** [comment] 2018-06-13 21:02
You can try the PR. I haven't confirmed it though.

**Comment by ajstocchetti** [comment] 2018-06-19 18:30
I tested @HotelCalifornia's PR and it worked. Until it gets merged in, I was able to get around this by manually setting the content length if its not:

```js
exports.handler = (event, context) => {
  // fix to deal with body being dropped on DELETE requests
  if (event.httpMethod === 'DELETE' && event.body && (!event.headers || !event.headers['Conent-Length'])) {
    console.log('Adding content length for DELETE body');
    event.headers = event.headers || {};
    event.headers['Content-Length'] = Buffer.byteLength(event.body);
  }
  return awsServerlessExpress.proxy(server, event, context);
}```

**Comment by brettstack** [comment] 2018-06-20 05:37
I'm working on integ tests right now and will merge that PR after they're in. Is the issue with API Gateway not sending the Content-Length header for DELETE requests with a body?

**Comment by HotelCalifornia** [comment] 2018-06-20 21:35
I think the issue is just that API gateway ignores the body in a DELETE request unless the Content-Length header is specified

**Comment by brettstack** [comment] 2018-06-20 22:09
I don't think that's what's happening. `event.body` is always coming through if you provide it in the request, right? My understanding is Express/Node.js http is throwing 502 when `body` exists with no `content-length` header in the request. So my assumption here is that API Gateway isn't including a `content-length` header for DELETE requests even when they have a body.

Your CR looks good. I just made a couple comments.

**Comment by HotelCalifornia** [comment] 2018-06-20 22:39
You're right, that does sound more correct. If I'm honest, it's been a few weeks since I've thought about this problem 😅

**Comment by brettstack** [comment] 2018-08-17 21:27
Closing in favor of #175. This will be out in the next release

**Closed by brettstack** 2018-08-17 21:27 UTC
Labels: bug
