### ISSUE TITLE
Async handler doesn't work on node 8.10

### ISSUE THREAD

**Issue by j0k3r** [awslabs/aws-serverless-express#134] opened 2018-04-04 14:01 UTC
I have reduced my project to that snippet which generates an error using the new 8.10:

```js
import awsServerlessExpress from 'aws-serverless-express'
import express from 'express'

export default async (event, context, callback) => {
  const app = express()

  app.get('/', function(req, res){
    res.send('hello world')
  })

  const server = awsServerlessExpress.createServer(app)

  return awsServerlessExpress.proxy(server, event, context)
}
```

Babel compilation targets node 8.10 to be sure it doesn't convert async/await to native js code.

Cloudwatch reports:

```
START RequestId: 3cb224ae-3810-11e8-ba0f-437e442fcf6a Version: $LATEST
Unable to stringify response body as json: Converting circular structure to JSON: TypeError

END RequestId: 3cb224ae-3810-11e8-ba0f-437e442fcf6a
REPORT RequestId: 3cb224ae-3810-11e8-ba0f-437e442fcf6a	Duration: 30027.56 ms	Billed Duration: 30000 ms 	Memory Size: 512 MB	Max Memory Used: 31 MB	
```

Removing the `async` in the handler fix the problem. But my whole project does some `await` in the handler which requires the handler to be async.

**Comment by brettstack** [comment] 2018-04-05 04:48
Feel free to re-open if there's still an issue.

**Comment by j0k3r** [comment] 2018-04-05 08:27
I know that removing the `async` fix the problem.
As I said, I've removed a lot of codes from my project to keep only what makes the lib to fail.

What if I have:

```js
import awsServerlessExpress from 'aws-serverless-express'
import express from 'express'
import configureApp from './configureApp'

export default async (event, context, callback) => {
  const app = express()

  await configureApp(app)

  app.get('/', function(req, res){
    res.send('hello world')
  })

  const server = awsServerlessExpress.createServer(app)

  return awsServerlessExpress.proxy(server, event, context)
}
```

Where `configureApp.js` is:

```js
import massive from 'massive'
import nconf from 'nconf'

const pgConfig = nconf.get('database').postgresql

export default async (application) => {
  const postgres = await massive(pgConfig)
  application.set('postgres', postgres)

  return application
}

```

That will generate the same error but I can't remove the `async` from the handler.

**Comment by brettstack** [comment] 2018-04-06 21:33
Okay so the problem is that Node.js 8.10 now allows you to resolve using Promises instead of the old `callback` and even older `context.succeed` (which this library uses). We did have a path forward for upgrading from `context.succeed` to `callback` by setting `context.callbackWaitsForEmptyEventLoop = true` (see #32) however, the new Promise pattern ignores that.

For now, you can't use Node.js 8.10 with an async handler (or return a promise). I'll update the library to work with the latest updates soon. Based on the examples you've provided so far, it's recommended to perform these setup tasks outside of the handler for best performance (that way these things happen only on cold start, and not on every invocation)

**Comment by josephktcheung** [comment] 2018-04-08 04:06
I've tried what @brettstack said and it works (I'm using `serverless-offline` so I use `process.env.IS_OFFLINE` to pass correct handler to `aws-serverless-express`):
```js
import * as serverless from 'aws-serverless-express';
import { ApplicationModule } from './modules/app/app.module';
import { Factory } from './app/some.factory';

export const handler = async (event, context) => {
  const app = await Factory.create(ApplicationModule, express);
  await app.init();
  const server = serverless.createServer(express);
  return new Promise((resolve, reject) => {
    serverless.proxy(server, event, {
      ...context,
      succeed: process.env.IS_OFFLINE ? context.succeed : resolve,
    });
  });
};

```

**Comment by brettstack** [comment] 2018-04-08 04:29
@josephktcheung glad to hear it worked. Regarding your code, you should always try to move setup tasks to outside of the handler. You should see significant performance improvements if you do this, but take care that your code still functions correctly on cold start.

**Comment by j0k3r** [comment] 2018-04-08 07:49
I'll give a try tomorrow. Thanks @josephktcheung to confirm that it worked.

Regarding moving stuff outside the handler, we usually do sth like that:

```js
import awsServerlessExpress from 'aws-serverless-express';
import express from 'express';
import configureApp from './configureApp';

let server

export default async (event, context) => {
  if (server) {
    return awsServerlessExpress.proxy(server, event, context)
  }

  const app = express();

  await configureApp(app);

  app.get('/', function(req, res){
    res.send('hello world');
  });

  server = awsServerlessExpress.createServer(app)

  return awsServerlessExpress.proxy(server, event, context)
}
```

Otherwise I don't know how can you move `await configureApp(app);` outside the handler since it's an async call.

**Comment by brettstack** [comment] 2018-04-08 18:50
@j0k3r that works fine since `server` exists outside of the `handler`. 👍

**Comment by brettstack** [comment] 2018-04-08 18:52
To support async handlers natively we'll need to bump major version since this will be a breaking change.

**Comment by j0k3r** [comment] 2018-04-08 18:57
@brettstack no problem about bumping 👍 
@josephktcheung that's an interesting way to handle initialization, thanks for sharing!

**Comment by j0k3r** [comment] 2018-05-01 20:10
@brettstack Any progress about async support?

**Comment by brettstack** [comment] 2018-05-01 21:27
I have it working in a local branch. Going to go with a non-breaking change and we'll improve the overall API of this project in the future in a major version bump. I first want to add some additional integration tests before I merge in support. SAM has been taking priority for me lately, but I do want to get this in. For now I suggest patching in support https://github.com/awslabs/aws-serverless-express/issues/134#issuecomment-379417431

**Comment by brettstack** [comment] 2018-08-14 16:35
PR for this here https://github.com/awslabs/aws-serverless-express/pull/173. Note that I plan on improving the interface in a future breaking change (aws-serverless-express 4.0.0), but for now this is a backwards compatible change with the following interface:

```js
exports.handler = async (event, context) => awsServerlessExpress.proxy(server, event, context, 'PROMISE')
```

**Comment by brettstack** [comment] 2018-08-16 23:18
Released in v3.3.3

**Closed by brettstack** 2018-08-16 23:18 UTC
Labels: enhancement

**Comment by j0k3r** [comment] 2018-08-22 09:02
I switched to what you did (and upgraded to 3.3.5):

```diff
-    return new Promise((resolve) => {
-      awsServerlessExpress.proxy(server, event, {
-        ...context,
-        succeed: resolve,
-      })
-    })
+    return awsServerlessExpress.proxy(server, event, context, 'PROMISE')
```

But now the APIGW returns 502 all the time. No error in log 😕

**Comment by brettstack** [comment] 2018-08-22 16:55
@j0k3r @Bnaya

Sorry, I goofed the guidance in that comment. Tack a `.promise` at the end of that line and you should be good to go.

Here's the test which covers this https://github.com/awslabs/aws-serverless-express/blob/master/__tests__/integration.js#L196-L200

And here's the implementation https://github.com/awslabs/aws-serverless-express/blob/master/src/index.js#L210-L230

You can see I'm returning `{ promise: new Promise...` instead of returning `new Promise...` directly. This decision was made for future extensibility.

**Comment by j0k3r** [comment] 2018-08-22 17:12
Oh great!
Yeah I'm aware of the `.promise()` in the AWS SDK already.
Sorry to bother you I didn't took the time to check the code.
Thanks!

**Comment by brettstack** [comment] 2018-10-14 16:01
I haven't tried with SAM CLI, but it works in Lambda if you are using the latest version of this package. I'll try to get some updated docs and add an init/quickstart over at SAM CLI.

**Comment by sgronblo** [comment] 2018-10-14 16:04
What do you mean by works in "Lambda"? As in the real Lambda on AWS? I noticed after responding here that this is not the repo for aws-sam-cli.

Should I be looking at some other issue for following the progress on this?

I also found this for example: https://github.com/awslabs/aws-sam-cli/issues/522 which might be what I am experiencing.

**Comment by brettstack** [comment] 2018-10-14 16:12
Sounds like that may be the Issue you're looking for. If you find it doesn't work in Lamdba (correct, I mean the one in AWS) please ping me again.

I don't currently have an integ test for application errors in Promise resolution mode (though I have one for the default callback mode https://github.com/awslabs/aws-serverless-express/blob/master/__tests__/integration.js#L413). I need to re-evaluate how I write these tests now that there exists multiple resolution modes. Copy/pasting the same test for different resolution modes isn't scalable like I have done with the happy path tests https://github.com/awslabs/aws-serverless-express/blob/master/__tests__/integration.js#L184

**Comment by sgronblo** [comment] 2018-10-14 16:14
Ok, thanks. So I guess my issue is similar however different. And yes, it does work this way in the real Lambda.

**Comment by smrgrg** [comment] 2018-10-24 03:50
I get unusual mysql connection timeout when I use async in hander for AWS Lambda. I think AWS Lambda handler does not like async (or is not compatible). Hence, preferred not to use async in handler module.exports function.

Does not work:
`module.exports.sampleXYZ = async (event, context, callback) => {
    await synchronousFunction();
    // Do something and return
};`

Works: 
`module.exports.sampleXYZ = (event, context, callback) => {
    call wrapperFunction();
    // Call wrapper function and do synchronous stuff over there
};`

Thanks.

**Comment by blueskycorner** [comment] 2018-10-31 22:48
Same as @smrgrg here. I get logs inside my async function but then nothing than the "internal server" error as a return.

Comparing with @j0k3r sample code, I'm not able to go after this line 

`await configureApp(app);`

**Comment by smrgrg** [comment] 2018-10-31 23:41
@blueskycorner After I removed my async in handler export function, I had to update my webpack. After that, it works like a charm. I had to manage my eslint configurations though.

**Comment by blueskycorner** [comment] 2018-11-05 20:32
Sorry for the last post. The problem was on my side. I'm still new in node js dev ... I missed to specify a callback in my async function (configureApp).
@smrgrg: No need for me to remove the async in the lambda. The example provided by @j0k3r works perfectly.

**Comment by oreshkoandrei** [comment] 2019-05-22 19:49
So, what is the relevant solution ? 3.3.6
tried everything from this discussion and still can't get async handler working (

**Comment by brettstack** [comment] 2019-05-23 00:51
`module.exports = awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise` should work

**Comment by oreshkoandrei** [comment] 2019-05-30 13:47
Yes, it works
Thx )

**Comment by boyankirov** [comment] 2019-06-19 16:08
Hey, thanks for providing the solution here !

Having this:
https://github.com/awslabs/aws-serverless-express/issues/134#issuecomment-495026574

In the Readme or a sample would help big time for future users.

**Comment by brettstack** [comment] 2019-06-19 20:50
Thanks. We're working towards v4 where this will be the default.

**Comment by kduraiswami** [comment] 2019-10-02 23:27
I am a little bit unclear on the solution here. Is it possible to resolve this issue if you are not running a server? I am just running serverless offline straight in the command line and the exposed handlers are all async. Thank you for the help.

**Comment by Craigfis** [comment] 2020-07-27 23:55
With @brettstack no longer at AWS it seems development here has stalled. Will plans for V4 be resurrected?

**Comment by er-dev** [comment] 2020-11-10 01:03
The solution posted by @brettstack does not work with the SAM-CLI (1.6.2) and Node 12.

The suggested solution is:
`exports.renderHandler = async (event: any, context: any) =>
  awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise`

Paired with a simple async Express route:
```tsx
app.use(async function renderRoute(req, res) {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/html; charset=utf-8')

  await AyncFunction()

  res.write('test')
  res.end()
})
```

This results in the error `ERR_STREAM_WRITE_AFTER_END`:

```
ERRORUncaught Exception       {"errorType":"Error","errorMessage":"write after end","code":"ERR_STREAM_WRITE_AFTER_END","stack":["Error [ERR_STREAM_WRITE_AFTER_END]: write after end","    at write_ (_http_outgoing.js:629:17)","    at ServerResponse.write (_http_outgoing.js:621:15)","    at renderRoute (/var/task/main.js:184:7)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at runNextTicks (internal/process/task_queues.js:66:3)","    at processImmediate (internal/timers.js:429:9)"]}
[ERROR] [1604969682004] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
Function 'ServerSideRenderFunction' timed out after 29 seconds
```

Running via `sam local start-api`, have not tried on Lambda.

**Comment by brettstack** [comment] 2021-01-11 02:28
I'm now supporting this project again. V4 RCs are available http://npmjs.com/package/@vendia/serverless-express

**Comment by repl-shenoy-sukumaran** [comment] 2021-08-13 12:58
How this can achive in version 4.3.x? 

```
const config = async initialize(); // this needs to be async
exports.handler = serverlessExpress({ app: createApp(config) });
```
