### ISSUE TITLE
Passing headers between services.

### ISSUE THREAD

**Issue by richburdon** [awslabs/aws-serverless-express#110] opened 2017-12-16 06:19 UTC
I have an auth service (using aws-serverless-express) that sets a header then redirects back to a calling service.

Setting a header directly causes a 500 error, so instead I'm trying to set a cookie and/or setting the Set-Cookie header.

~~~~
res.cookie('jwt', 'xxx', { domain: 'mydomain.com' });
res.header('Set-Cookie', 'XXX=ZZZ');
res.redirect(callingUrl)   
~~~~

But neither the cookie nor the header are visible in the calling service (which is also using aws-serverless-express).

Is this possible? Is there another way?

Thanks.

**Comment by efortes** [comment] 2018-02-16 11:46
Yes I have the same problem. I can't see my cookies.

**Comment by brettstack** [comment] 2018-02-16 15:04
Have you checked CloudWatch for the actual error?

**Comment by efortes** [comment] 2018-02-17 12:09
I checked CloudWatch and I don't see any errors. The Response headers in my request seems to be alright aswell. Any what i'm doing wrong?

**My response headers**:
`
access-control-allow-credentials:true
access-control-allow-headers:Content-Type, Authorization, Content-Length, X-Requested-With, x-http-method-override, cookie, authorization
access-control-allow-methods:GET,PUT,POST,DELETE,OPTIONS,PATCH
access-control-allow-origin:https://*
content-length:741
content-type:application/json; charset=utf-8
date:Sat, 17 Feb 2018 11:54:32 GMT
etag:W/"2e5-eksB1oojVIcGEGQaRe/HU6gknNQ"
set-cookie:authJWT=*; Path=/; Secure
status:200
via:1.1 84181e9506b7e75393f77c574cba4387.cloudfront.net (CloudFront)
x-amz-cf-id:_qOTpBJXSJDl3viyaBeoaxzAU_zrLmBSA9UgHz87-xrsYr4XQsVcvA==
x-amzn-remapped-connection:close
x-amzn-remapped-content-length:741
x-amzn-remapped-date:Sat, 17 Feb 2018 11:54:32 GMT
x-amzn-requestid:50eb2a12-13d9-11e8-9ba5-2b6f65aeca09
x-amzn-trace-id:sampled=1;root=1-5a8817f8-a3f4427f08d527e2404cb6e7
x-cache:Miss from cloudfront
x-powered-by:Express 
`

My cloud watch response:
`
{
    "resource": "/{ebinde-api+}",
    "path": "/availability/login",
    "httpMethod": "POST",
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "nl,en-US;q=0.9,en;q=0.8",
        "cache-control": "no-cache",
        "CloudFront-Forwarded-Proto": "https",
        "CloudFront-Is-Desktop-Viewer": "true",
        "CloudFront-Is-Mobile-Viewer": "false",
        "CloudFront-Is-SmartTV-Viewer": "false",
        "CloudFront-Is-Tablet-Viewer": "false",
        "CloudFront-Viewer-Country": "NL",
        "content-type": "application/json",
        "Host": "*.execute-api.eu-central-1.amazonaws.com",
        "origin": "*",
        "pragma": "no-cache",
        "Referer": "*",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
        "Via": "2.0 84181e9506b7e75393f77c574cba4387.cloudfront.net (CloudFront)",
        "X-Amz-Cf-Id": "zwMkrBdXhYPAaF9s46yjjdUTQA9ccg6oJ5svCm8pD6YK7jWNdNtOZg==",
        "X-Amzn-Trace-Id": "Root=1-5a8817f8-1a039826e5adc23eb065ef50",
        "X-Forwarded-For": "217.*, 54.*",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "queryStringParameters": null,
    "pathParameters": {
        "ebinde-api": "availability/login"
    },
    "stageVariables": null,
    "requestContext": {
        "requestTime": "17/Feb/2018:11:54:32 +0000",
        "path": "/prod/availability/login",
        "accountId": "130152548732",
        "protocol": "HTTP/1.1",
        "resourceId": "zo643i",
        "stage": "prod",
        "requestTimeEpoch": 1518868472122,
        "requestId": "50eb2a12-13d9-11e8-9ba5-2b6f65aeca09",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "sourceIp": "217.*",
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
            "user": null
        },
        "resourcePath": "/{ebinde-api+}",
        "httpMethod": "POST",
        "apiId": "gmzf3pr455"
    },
    "body": "{\"idToken\":\"**\",\"type\":\"google\"}",
    "isBase64Encoded": false
}
`

**Comment by brettstack** [comment] 2018-02-17 14:36
No, that looks fine. If you're getting a response log for Lambda then your Lambda is succeeding (you can check the Lambda console for your function and click the monitoring tab to verify there are no errors). The error then must be at the API Gateway layer. Can you check those logs? You will need to enable logs on your API stage

**Comment by efortes** [comment] 2018-02-20 21:43
Thank you for the tip @brettstack . I enabled the logging and I did not see anything strange. The cookie is just not set (It is set when I run the app on my local machine without lambda).
I have no clue what is causing this issue.

**Comment by williscool** [comment] 2018-05-10 23:02
have this problem too. 

I know its something near express because if I just 

```
curl --head http://localhost:3000/
```

My server with serverless offline I don't get the cookie I set

**Comment by williscool** [comment] 2018-07-09 01:42
I'm pretty sure It related 

to 

"If the backend is attempting to send multiple cookie values using multiple "Set-Cookie" headers, then that will not work currently with API Gateway. While that is perfectly valid behavior for cookies, we only support unique headers at the moment. "

https://forums.aws.amazon.com/thread.jspa?threadID=205782

So gotta figure out a way to set all cookies in one call to set-cookie :/

**Comment by brettstack** [comment] 2018-08-18 14:25
@efortes did you ever resolve this? I notice that your "My cloud watch response:" is actually a log of your request event

**Comment by brettstack** [comment] 2018-08-18 14:26
Also the multiple header issue is fixed by this https://github.com/awslabs/aws-serverless-express/blob/master/src/index.js#L70

**Comment by stepri** [comment] 2018-09-13 16:28
I'm having the same problem.. Only the first cookie is set

**Comment by brettstack** [comment] 2018-09-13 16:50
@stepri could you explain what you're trying to do, how you're doing it, what's the expected result, and what's the actual result?

**Comment by stepri** [comment] 2018-09-13 17:01
I'm using express, serverless, serverless-offline, cookie-session and aws-serverless-express. Only the `session.sig` is returned by the server. Not the session with the data itself. I have the following setup:

```js
const express = require('express')
const serverless = require('serverless-http');
const cookieSession = require('cookie-session')

const app = express()

app.use(cookieSession({
  name: 'session',
  secret: 'asdfasdfasdfasdf'
}))

app.get('/test', (req, res) => {
  req.session.views = (req.session.views || 0) + 1
  return res.end(req.session.views + ' views')
})

module.exports.handler = serverless(app);
```

```
service: myservice

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

```

I run the following command:
```serverless offline```

In the example I expect the counter to be increasing, but the counter stays the same.

**Comment by stepri** [comment] 2018-09-13 17:07
Oops, it's running some old code. It's working now.

**Comment by brettstack** [comment] 2018-09-13 17:56
Glad you figured it out. Is there a specific reason you moved from serverless-http to this package?

**Comment by stepri** [comment] 2018-09-14 20:31
The same problem (not all cookies returned by server) is back. I have the following files:

lambda.js (from README.md)
```js
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./test')
const server = awsServerlessExpress.createServer(app)

exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```

test.js
```js
const express = require('express')
const cookieSession = require('cookie-session')

const app = express()

app.use(cookieSession({
  secret: 'testingSecretCookie'
}))

app.get('/test', (req, res) => {
  req.session.views = (req.session.views || 0) + 1
  return res.end(req.session.views + ' views')
})

module.exports = app;
```

serverless.yml
```yaml
service: contactsdrop

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  app:
    handler: test.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```

Again, I expect the counter to be increasing, but the counter stays the same. Only the signature cookie is being returned. Starting the server with `sls offline`. Do I miss something here?

**Comment by brettstack** [comment] 2018-09-15 03:28
You can't effectively use sessions with Lambda. The containers are ephemeral.

**Comment by efortes** [comment] 2018-09-27 13:19
@brettstack sorry for the late reply. I did finish my feature but I don't remember what the fix was.

**Comment by brettstack** [comment] 2018-09-29 15:16
Closing as OP has not responded and others in this thread have identified their problem as not related to this package.

**Closed by brettstack** 2018-09-29 15:16 UTC

**Comment by tao1** [comment] 2020-08-24 21:37
Well 2 years after this bug was closed, I am still facing a problem with cookies not set by lambdas exposed through api gateway.
But I am glad, now I know the problem is not coming from this package. And stackoverflow has tons of solutions wasting my time.
A response to @stepri would enlighten me.
